alias stats {
  query = [ $+ [ $1 ] ] 14=================================================
  query = [ $+ [ $1 ] ] 14= Name: %char [ $+ [ $nick ] ] $str($chr(160),$calc(14 - $len(%char [ $+ [ $nick ] ]))) 14= Race: $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,info,race) $str($chr(160),$calc(14 - $len($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,info,race)))) 14=
  query = [ $+ [ $1 ] ] 14= Element: $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,info,element) $str($chr(160),$calc(11 - $len($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,info,element)))) 14= Class: $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,info,class) $str($chr(160),$calc(13 - $len($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,info,class)))) 14=
  query = [ $+ [ $1 ] ] 14=================================================
  query = [ $+ [ $1 ] ] 14= Strength: $str($chr(160),$calc(10 - $len($floor($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,str))))) $iif($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,str) > $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,nstats,str),12) $+ $iif($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,str) < $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,nstats,str),4) $+ $floor($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,str)) 14= Vitality: $str($chr(160),$calc(10 - $len($floor($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,vit))))) $iif($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,vit) > $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,nstats,vit),12) $+ $iif($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,vit) < $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,nstats,vit),4) $+ $floor($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,vit)) 14=
  query = [ $+ [ $1 ] ] 14= Dexterity: $str($chr(160),$calc(9 - $len($floor($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,dex))))) $iif($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,dex) > $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,nstats,dex),12) $+ $iif($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,dex) < $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,nstats,dex),4) $+ $floor($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,dex)) 14= Agility: $str($chr(160),$calc(11 - $len($floor($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,agi))))) $iif($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,agi) > $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,nstats,agi),12) $+ $iif($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,agi) < $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,nstats,agi),4) $+ $floor($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,agi)) 14=
  query = [ $+ [ $1 ] ] 14= Intelligence: $str($chr(160),$calc(6 - $len($floor($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,int))))) $iif($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,int) > $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,nstats,int),12) $+ $iif($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,int) < $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,nstats,int),4) $+ $floor($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,int)) 14= Willpower: $str($chr(160),$calc(9 - $len($floor($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,wil))))) $iif($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,wil) > $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,nstats,wil),12) $+ $iif($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,wil) < $readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,nstats,wil),4) $+ $floor($readini(char\ $+ %char [ $+ [ $nick ] ] $+ .chr,cstats,wil)) 14=
  query = [ $+ [ $1 ] ] 14=================================================
}

alias look {
  if ( $2 != $null ) {
    query = [ $+ [ $1 ] ] Look coming soon. You specified10 $2 $+ .
  }
  else { query = [ $+ [ $1 ] ] Look coming soon. Looking at the room. }
}
